# This file was automatically generated by pywxrc, do not edit by hand.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res


class xrcMentokFrame(wx.Frame):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "MentokFrame")
        self.PostCreate(pre)

        # Define variables for the controls
        self.mypanel = xrc.XRCCTRL(self, "mypanel")



# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    mentok_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="MentokFrame">
    <title>Mentok The MindTrainer</title>
    <object class="wxPanel" name="mypanel"/>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/mentok/mentok_xrc', mentok_xrc)
    __res.Load('memory:XRC/mentok/mentok_xrc')

